CREATE DATABASE UEFA_CHAMPIONS_LEAGUE_2016_2022;

-- Chaves primarias sem a possibilidade de receber dados vazios.
ALTER TABLE TEAMS
ALTER COLUMN TEAM_NAME VARCHAR(50) NOT NULL;

ALTER TABLE PLAYERS
ALTER COLUMN PLAYER_ID VARCHAR(50) NOT NULL;

ALTER TABLE MANAGERS
ALTER COLUMN LAST_NAME VARCHAR(50) NOT NULL;

ALTER TABLE MATCHES
ALTER COLUMN MATCH_ID VARCHAR(50) NOT NULL;

ALTER TABLE GOALS
ALTER COLUMN GOAL_ID VARCHAR(50) NOT NULL;

ALTER TABLE STADIUMS
ALTER COLUMN NAME VARCHAR(50) NOT NULL;

ALTER TABLE TEAM_LOGO
ALTER COLUMN LOGO_ID VARCHAR(50) NOT NULL;