-- Definição das chaves primarias de cada tabela
ALTER TABLE TEAMS
ADD CONSTRAINT PK_Teams PRIMARY KEY (TEAM_NAME);

ALTER TABLE STADIUMS
ADD CONSTRAINT PK_Stadiums PRIMARY KEY (NAME);

ALTER TABLE PLAYERS
ADD CONSTRAINT PK_Players PRIMARY KEY (PLAYER_ID);

ALTER TABLE MANAGERS
ADD CONSTRAINT PK_Managers PRIMARY KEY (LAST_NAME); 

ALTER TABLE MATCHES
ADD CONSTRAINT PK_Matches PRIMARY KEY (MATCH_ID);

ALTER TABLE GOALS
ADD CONSTRAINT PK_Goals PRIMARY KEY (GOAL_ID);

ALTER TABLE TEAM_LOGO
ADD CONSTRAINT PK_Team_Logo PRIMARY KEY (LOGO_ID);