-- Denifinição das chaves estrangeiras
ALTER TABLE TEAMS
ADD CONSTRAINT FK_Teams_Stadiums FOREIGN KEY (HOME_STADIUM) REFERENCES Stadiums (NAME);

ALTER TABLE Players
ADD CONSTRAINT FK_Players_Teams FOREIGN KEY (TEAM) REFERENCES Teams(TEAM_NAME);

ALTER TABLE Managers
ADD CONSTRAINT FK_Managers_Teams FOREIGN KEY (TEAM) REFERENCES Teams(TEAM_NAME);

ALTER TABLE Matches
ADD CONSTRAINT FK_Matches_HomeTeam FOREIGN KEY (HOME_TEAM) REFERENCES Teams(TEAM_NAME),
    CONSTRAINT FK_Matches_AwayTeam FOREIGN KEY (AWAY_TEAM) REFERENCES Teams(TEAM_NAME);

ALTER TABLE Matches
ADD CONSTRAINT FK_Matches_Stadium FOREIGN KEY (STADIUM) REFERENCES Stadiums(NAME);

ALTER TABLE Goals
ADD CONSTRAINT FK_Goals_Matches FOREIGN KEY (MATCH_ID) REFERENCES Matches(MATCH_ID);

ALTER TABLE Team_logo
ADD CONSTRAINT FK_Team_logo_Teams FOREIGN KEY (TEAM_NAME) REFERENCES Teams(TEAM_NAME);