ALTER TABLE MATCHES
ALTER COLUMN HOME_TEAM_SCORE INT;

ALTER TABLE MATCHES
ALTER COLUMN AWAY_TEAM_SCORE INT;

SELECT  
    T1.TEAM_NAME,
    SUM(CASE WHEN HOME_TEAM = T1.TEAM_NAME THEN HOME_TEAM_SCORE ELSE 0 END) AS GOLS_EM_CASA,
    SUM(CASE WHEN AWAY_TEAM = T2.TEAM_NAME THEN AWAY_TEAM_SCORE ELSE 0 END) AS GOLS_FORA,
    SUM(CASE WHEN HOME_TEAM = T1.TEAM_NAME THEN HOME_TEAM_SCORE ELSE 0 END) +
    SUM(CASE WHEN AWAY_TEAM = T2.TEAM_NAME THEN AWAY_TEAM_SCORE ELSE 0 END) AS TOTAL_GOLS
FROM MATCHES
LEFT JOIN TEAMS AS T1 ON HOME_TEAM = T1.TEAM_NAME
LEFT JOIN TEAMS AS T2 ON AWAY_TEAM = T2.TEAM_NAME
GROUP BY T1.TEAM_NAME
ORDER BY TOTAL_GOLS DESC;
