SELECT 
    HOME_TEAM AS TEAM,
    SUM(CASE WHEN HOME_TEAM_SCORE > AWAY_TEAM_SCORE THEN 1 ELSE 0 END) AS TOTAL_VITORIAS_EM_CASA,
    SUM(CASE WHEN HOME_TEAM_SCORE < AWAY_TEAM_SCORE THEN 1 ELSE 0 END) AS TOTAL_VITORIAS_FORA,
    SUM(CASE WHEN HOME_TEAM_SCORE > AWAY_TEAM_SCORE THEN 1 ELSE 0 END) + 
    SUM(CASE WHEN HOME_TEAM_SCORE < AWAY_TEAM_SCORE THEN 1 ELSE 0 END) AS TOTAL_VITORIAS
FROM MATCHES
GROUP BY HOME_TEAM
ORDER BY TOTAL_VITORIAS DESC;
