ALTER TABLE STADIUMS 
ALTER COLUMN CAPACITY INT;

ALTER TABLE MATCHES
ALTER COLUMN ATTENDANCE INT;

SELECT NAME, M.HOME_TEAM, M.AWAY_TEAM, S.CITY, S.COUNTRY, S.CAPACITY, M.ATTENDANCE,
M.ATTENDANCE * 1.0 / S.CAPACITY * 100 AS PORCENTAGEM_OCUPAÇÃO
FROM STADIUMS AS S INNER JOIN MATCHES AS M 
ON S.NAME = M.STADIUM
WHERE HOME_TEAM = 'Manchester City'
ORDER BY PORCENTAGEM_OCUPAÇÃO DESC;